<Project Sdk="MSTest.Sdk">
  <ItemGroup>
    <AssemblyMetadata Include="AnkusTestSdkVersion" Value="$(NETCoreSdkVersion)" />
    <AssemblyMetadata Include="AnkusTestSdkDirectory" Value="$(MSBuildToolsPath)" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <ProjectReference Include="..\..\src\Ankus.Build\Ankus.Build.csproj" />
    <ProjectReference Include="..\..\src\Ankus.Runtime\Ankus.Runtime.csproj" />
    <None Include="../../src/Ankus.Sdk/Ankus.props" Link="Sdk/Ankus.props" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/Ankus.Sdk/targets/Ankus.Bindings.targets" Link="Sdk/Ankus.Bindings.targets" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/Ankus.Sdk/targets/Ankus.Development.targets" Link="Sdk/Ankus.Development.targets" CopyToOutputDirectory="PreserveNewest" />
    <None Include="../../src/Ankus.Sdk/targets/Ankus.Native.targets" Link="Sdk/Ankus.Native.targets" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <PropertyGroup>
    <EnableMSTestSourceGeneration>true</EnableMSTestSourceGeneration>
  </PropertyGroup>
</Project>
