<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <RootNamespace>Ankus.Build.Tests</RootNamespace>
    <MSTestAnalysisMode>Recommended</MSTestAnalysisMode>
    <EnableMSTestSourceGeneration>true</EnableMSTestSourceGeneration>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Ankus.Build/Ankus.Build.csproj" />
  </ItemGroup>
</Project>
