namespace Ankus.Build.Tests;

public sealed partial class NativeBindingCacheTests
{
    /// <summary>
    /// Cache hits refresh recency and eviction keeps the most recently consumed entries within the byte budget.
    /// </summary>
    [TestMethod]
    public async Task CacheRetentionEvictsOldestAndRefreshesHits()
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-retention-").FullName;
        try
        {
            string[] keys = [new('A', 64), new('B', 64), new('C', 64)];
            for (int index = 0; index < keys.Length; index++)
            {
                await using (NativeBindingCacheLease lease = await NativeBindingCache.GetAsync(root, keys[index], RetentionArtifactAsync,
                    context.CancellationToken))
                {
                    Assert.AreEqual("retained bytes", await File.ReadAllTextAsync(Path.Combine(lease.Directory, "binding.dll"), context.CancellationToken));
                }

                Directory.SetLastWriteTimeUtc(Path.Combine(root, keys[index]), new DateTime(2020, 1, index + 1, 0, 0, 0, DateTimeKind.Utc));
            }

            await using (NativeBindingCacheLease refreshed = await NativeBindingCache.GetAsync(root, keys[0],
                static (_, _) => throw new AssertFailedException("An unchanged hit must not invoke the producer."), context.CancellationToken))
            {
                Assert.AreEqual(Path.Combine(root, keys[0]), refreshed.Directory);
            }

            long retainedBytes = EntryBytes(Path.Combine(root, keys[0])) + EntryBytes(Path.Combine(root, keys[2]));
            await NativeBindingCache.TrimAsync(root, retainedBytes, context.CancellationToken);
            Assert.IsFalse(Directory.Exists(Path.Combine(root, keys[1])));
            Assert.IsTrue(Directory.Exists(Path.Combine(root, keys[0])));
            Assert.IsTrue(Directory.Exists(Path.Combine(root, keys[2])));
            Assert.AreEqual(retainedBytes, Directory.GetDirectories(root).Sum(EntryBytes));
            Assert.IsTrue(File.Exists(Path.Combine(root, keys[1] + ".lock")));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>
    /// Trimming cannot remove leased bytes, but can reclaim and regenerate them after the last reader finishes.
    /// </summary>
    [TestMethod]
    public async Task CacheRetentionProtectsLeasesAndRebuildsEvictedEntries()
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-active-").FullName;
        try
        {
            await using (NativeBindingCacheLease lease = await NativeBindingCache.GetAsync(root, Key, RetentionArtifactAsync,
                context.CancellationToken))
            {
                await NativeBindingCache.TrimAsync(root, 0, context.CancellationToken);
                Assert.AreEqual("retained bytes", await File.ReadAllTextAsync(Path.Combine(lease.Directory, "binding.dll"), context.CancellationToken));
            }

            await NativeBindingCache.TrimAsync(root, 0, context.CancellationToken);
            Assert.IsEmpty(Directory.GetDirectories(root));
            await using NativeBindingCacheLease rebuilt = await NativeBindingCache.GetAsync(root, Key, async (stage, token) =>
            {
                await File.WriteAllTextAsync(Path.Combine(stage, "binding.dll"), "regenerated bytes", token);
                return [];
            }, context.CancellationToken);
            Assert.AreEqual("regenerated bytes", await File.ReadAllTextAsync(Path.Combine(rebuilt.Directory, "binding.dll"), context.CancellationToken));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>
    /// Abandoned staging is reclaimed while active staging, unrelated directories and other stores remain untouched.
    /// </summary>
    [TestMethod]
    public async Task CacheRetentionOnlyRemovesOwnedIdleDirectories()
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-staging-").FullName;
        try
        {
            string activeKey = new('D', 64);
            string[] kept = [Path.Combine(root, "unrelated"), Path.Combine(root, "sources"),
                Path.Combine(root, Key + ".stage-not-a-guid"), Path.Combine(root, activeKey + ".stage-" + Guid.NewGuid().ToString("N"))];
            string[] removed = [Path.Combine(root, Key + ".stage-" + Guid.NewGuid().ToString("N")),
                Path.Combine(root, Key + ".replaced-" + Guid.NewGuid().ToString("N"))];
            foreach (string path in kept.Concat(removed))
            {
                Directory.CreateDirectory(path);
                await File.WriteAllTextAsync(Path.Combine(path, "sentinel"), "owned bytes", context.CancellationToken);
            }

            await using var active = new FileStream(Path.Combine(root, activeKey + ".lock"), FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None);
            await NativeBindingCache.TrimAsync(root, 0, context.CancellationToken);
            Assert.DoesNotContain(Directory.Exists, removed);
            foreach (string path in kept)
            {
                Assert.AreEqual("owned bytes", await File.ReadAllTextAsync(Path.Combine(path, "sentinel"), context.CancellationToken));
            }
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>
    /// Competing maintenance does not wait while holding a consumer's lease, and later maintenance makes progress.
    /// </summary>
    [TestMethod]
    public async Task CacheRetentionSkipsBusyMaintenance()
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-maintenance-").FullName;
        try
        {
            await using (NativeBindingCacheLease lease = await NativeBindingCache.GetAsync(root, Key, RetentionArtifactAsync,
                context.CancellationToken))
            {
                Assert.IsTrue(Directory.Exists(lease.Directory));
            }

            await using (var maintenance = new FileStream(Path.Combine(root, ".retention.lock"), FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None))
            {
                await NativeBindingCache.TrimAsync(root, 0, context.CancellationToken);
                Assert.IsTrue(Directory.Exists(Path.Combine(root, Key)));
            }

            await NativeBindingCache.TrimAsync(root, 0, context.CancellationToken);
            Assert.IsFalse(Directory.Exists(Path.Combine(root, Key)));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>
    /// A cache-shaped directory link cannot make eviction delete files outside the owned store.
    /// </summary>
    [TestMethod]
    [OSCondition(OperatingSystems.Linux | OperatingSystems.OSX)]
    public async Task CacheRetentionDoesNotFollowDirectoryLinks()
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-external-").FullName;
        try
        {
            string external = Path.Combine(root, "external");
            string cache = Path.Combine(root, "cache");
            Directory.CreateDirectory(external);
            Directory.CreateDirectory(cache);
            string sentinel = Path.Combine(external, "keep");
            await File.WriteAllTextAsync(sentinel, "external bytes", context.CancellationToken);
            Directory.CreateSymbolicLink(Path.Combine(cache, Key), external);
            await NativeBindingCache.TrimAsync(cache, 0, context.CancellationToken);
            Assert.AreEqual("external bytes", await File.ReadAllTextAsync(sentinel, context.CancellationToken));
            Assert.IsTrue(File.GetAttributes(Path.Combine(cache, Key)).HasFlag(FileAttributes.ReparsePoint));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>
    /// Retention accepts explicit positive byte budgets and preserves the bounded default when unset.
    /// </summary>
    /// <param name="value">The configured environment value.</param>
    /// <param name="expected">The selected byte budget.</param>
    [TestMethod]
    [DataRow(null, 2147483648L)]
    [DataRow("", 2147483648L)]
    [DataRow("1", 1L)]
    [DataRow("4294967296", 4294967296L)]
    public void CacheRetentionReadsByteBudget(string? value, long expected)
        => Assert.AreEqual(expected, NativeBindingCache.ReadMaximumBytes(value));

    /// <summary>
    /// Invalid configuration fails explicitly instead of silently making storage unbounded.
    /// </summary>
    /// <param name="value">The malformed byte budget.</param>
    [TestMethod]
    [DataRow("0")]
    [DataRow("-1")]
    [DataRow("two GiB")]
    [DataRow("9223372036854775808")]
    public void CacheRetentionRejectsInvalidBudget(string value)
    {
        FormatException error = Assert.ThrowsExactly<FormatException>(() => NativeBindingCache.ReadMaximumBytes(value));
        Assert.Contains("ANKUS_BINDING_CACHE_MAX_BYTES", error.Message);
    }

    /// <summary>
    /// Releasing copied artifacts applies retention automatically, while retained linker inputs stay usable.
    /// </summary>
    /// <param name="copied">Whether the consumer has copied the leased artifacts.</param>
    [TestMethod]
    [DataRow(true)]
    [DataRow(false)]
    public async Task CacheLeaseDisposalHonorsArtifactLifetime(bool copied)
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-disposal-").FullName;
        try
        {
            await using (NativeBindingCacheLease initial = await NativeBindingCache.GetAsync(root, Key, RetentionArtifactAsync,
                context.CancellationToken))
            {
                Assert.IsTrue(Directory.Exists(initial.Directory));
            }

            string entry = Path.Combine(root, Key);
            var ownership = new FileStream(Path.Combine(root, Key + ".lock"), FileMode.Open, FileAccess.ReadWrite, FileShare.None);
            await using (var lease = new NativeBindingCacheLease(entry, ownership, copied ? root : null, 0))
            {
                Assert.AreEqual("retained bytes", await File.ReadAllTextAsync(Path.Combine(lease.Directory, "binding.dll"), context.CancellationToken));
            }

            Assert.AreEqual(!copied, Directory.Exists(entry));
            if (!copied)
            {
                Assert.AreEqual("retained bytes", await File.ReadAllTextAsync(Path.Combine(entry, "binding.dll"), context.CancellationToken));
            }
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    /// <summary>
    /// Cancellation before maintenance preserves the existing entry and leaves its lock available.
    /// </summary>
    [TestMethod]
    public async Task CacheRetentionCancellationPreservesArtifacts()
    {
        string root = Directory.CreateTempSubdirectory("ankus-cache-cancel-").FullName;
        try
        {
            await using (NativeBindingCacheLease initial = await NativeBindingCache.GetAsync(root, Key, RetentionArtifactAsync,
                context.CancellationToken))
            {
                Assert.IsTrue(Directory.Exists(initial.Directory));
            }

            using var cancellation = CancellationTokenSource.CreateLinkedTokenSource(context.CancellationToken);
            await cancellation.CancelAsync();
            await Assert.ThrowsExactlyAsync<OperationCanceledException>(() => NativeBindingCache.TrimAsync(root, 0, cancellation.Token));
            Assert.AreEqual("retained bytes", await File.ReadAllTextAsync(Path.Combine(root, Key, "binding.dll"), context.CancellationToken));
            await NativeBindingCache.TrimAsync(root, 0, context.CancellationToken);
            Assert.IsEmpty(Directory.GetDirectories(root));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    private static long EntryBytes(string path) => Directory.GetFiles(path).Sum(static file => new FileInfo(file).Length);

    private static async Task<IReadOnlyList<NativeBindingCacheFile>> RetentionArtifactAsync(string stage, CancellationToken token)
    {
        await File.WriteAllTextAsync(Path.Combine(stage, "binding.dll"), "retained bytes", token);
        return [];
    }
}
