<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <RootNamespace>Ankus.PgConfig.Tests</RootNamespace>
    <EnableMSTestSourceGeneration>true</EnableMSTestSourceGeneration>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Ankus.PgConfig/Ankus.PgConfig.csproj" />
  </ItemGroup>

</Project>
