using System.Buffers.Binary;
using System.Text;

namespace Ankus.PgConfig.Tests;

public sealed partial class ExtensionSchemaGraphTests
{
    /// <summary>
    /// A versioned preamble and annotated fragments survive full, attached and detached extraction.
    /// </summary>
    /// <param name="attach">Whether selected objects are attached to the extension.</param>
    [TestMethod]
    [DataRow(false)]
    [DataRow(true)]
    public void ProvenancePreambleSurvivesSelection(bool attach)
    {
        const string Header = "-- Generated by independent fixture.\n\n";
        const string Fragment = "-- Queries.cs:17\n-- Demo.Query()\nSELECT 'exact'; -- trailing\n";
        ExtensionSchema schema = Schema(EncodeWithPreamble(Header, new("query", "function", Fragment,
            Names: ["query"], Attachments: ["FUNCTION query()"]), new("other", "sql", "SELECT 2;", Names: ["other"])));
        Assert.AreEqual(Header + Fragment + "SELECT 2;\n", schema.Sql);
        ExtensionSchemaSelection selected = schema.Select(["query"], attach);
        Assert.AreEqual(Header + (attach ? "BEGIN;\n\n" : string.Empty) + Fragment +
            (attach ? "ALTER EXTENSION \"probe\" ADD FUNCTION query();\n\nCOMMIT;\n" : string.Empty), selected.Sql);
        Assert.AreEqual(Fragment, Assert.ContainsSingle(selected.Items).Sql);
        Assert.IsEmpty(selected.Warnings);
    }

    /// <summary>
    /// The preamble never makes a disabled declaration look installable or invents an attachment.
    /// </summary>
    [TestMethod]
    public void ProvenancePreamblePreservesEmptyAndDisabledGraphs()
    {
        const string Header = "-- generated\n\n";
        ExtensionSchemaGraph empty = ExtensionSchemaGraph.Parse(EncodeWithPreamble(Header));
        Assert.AreEqual(Header + "-- No installable objects declared.\n", empty.Sql);
        Assert.IsEmpty(empty.Items);
        ExtensionSchema schema = Schema(EncodeWithPreamble(Header,
            new Entry("query", "function", "", Names: ["query"], Attachments: ["FUNCTION query()"] )));
        Assert.AreEqual(empty.Sql, schema.Sql);
        Assert.AreEqual(Header + "BEGIN;\n\n\nCOMMIT;\n", schema.Select(["query"]).Sql);
        Assert.AreEqual(Header, schema.Select(["query"], alterExtension: false).Sql);
    }

    /// <summary>
    /// Every preamble and declaration truncation is rejected rather than read as a legacy or empty graph.
    /// </summary>
    [TestMethod]
    public void ProvenanceGraphRejectsEveryTruncation()
    {
        byte[] bytes = Convert.FromBase64String(EncodeWithPreamble("-- café 🐘\n", new Entry("query", "sql", "SELECT 1;")));
        for (int length = 0; length < bytes.Length; length++)
        {
            string truncated = Convert.ToBase64String(bytes.AsSpan(0, length));
            Assert.ThrowsExactly<FormatException>(() => ExtensionSchemaGraph.Parse(truncated));
        }
    }

    /// <summary>
    /// The preamble cannot bypass UTF-8 validation, embedded zero rejection or length framing.
    /// </summary>
    /// <param name="failure">The invalid wire field.</param>
    [TestMethod]
    [DataRow("utf8")]
    [DataRow("nul")]
    [DataRow("length")]
    [DataRow("version")]
    public void ProvenanceGraphRejectsInvalidPreamble(string failure)
    {
        byte[] bytes = Convert.FromBase64String(EncodeWithPreamble("-- header\n", new Entry("query", "sql", "SELECT 1;")));
        switch (failure)
        {
            case "utf8":
                bytes[12] = 255;
                break;
            case "nul":
                bytes[12] = 0;
                break;
            case "length":
                BinaryPrimitives.WriteInt32LittleEndian(bytes.AsSpan(8), int.MaxValue);
                break;
            case "version":
                bytes[6] = (byte)'3';
                break;
        }

        Assert.ThrowsExactly<FormatException>(() => ExtensionSchemaGraph.Parse(Convert.ToBase64String(bytes)));
    }

    /// <summary>
    /// Preamble bytes participate in the existing total allocation limit, including its exact endpoint.
    /// </summary>
    /// <param name="offset">The distance from the maximum graph byte count.</param>
    [TestMethod]
    [DataRow(-1)]
    [DataRow(0)]
    [DataRow(1)]
    public void ProvenanceGraphEnforcesTotalByteBoundary(int offset)
    {
        const int Maximum = 32 * 1024 * 1024;
        const string Header = "-- source café\n";
        int overhead = Convert.FromBase64String(EncodeWithPreamble(Header, new Entry("query", "sql", ""))).Length;
        int length = Maximum - overhead + offset;
        string encoded = EncodeWithPreamble(Header, new Entry("query", "sql", new string(' ', length)));
        Assert.HasCount(Maximum + offset, Convert.FromBase64String(encoded));
        if (offset > 0)
        {
            Assert.ThrowsExactly<FormatException>(() => ExtensionSchemaGraph.Parse(encoded));
        }
        else
        {
            ExtensionSchemaGraph graph = ExtensionSchemaGraph.Parse(encoded);
            Assert.AreEqual(Header + new string(' ', length) + "\n", graph.Sql);
            Assert.AreEqual(length, Assert.ContainsSingle(graph.Items).Sql.Length);
        }
    }

    /// <summary>
    /// Writes the second graph format independently, reusing only the existing legacy fixture's node fields.
    /// </summary>
    private static string EncodeWithPreamble(string preamble, params Entry[] entries)
    {
        byte[] previous = Convert.FromBase64String(Encode(entries));
        byte[] text = Encoding.UTF8.GetBytes(preamble);
        byte[] bytes = new byte[previous.Length + 4 + text.Length];
        "ANKUSG2\0"u8.CopyTo(bytes);
        BinaryPrimitives.WriteInt32LittleEndian(bytes.AsSpan(8), text.Length);
        text.CopyTo(bytes, 12);
        previous.AsSpan(8).CopyTo(bytes.AsSpan(12 + text.Length));
        return Convert.ToBase64String(bytes);
    }
}
