<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>A PostgreSQL background worker with managed transactions and shared observations.</Description>
    <AnkusExtensionName>ankus_background_workers</AnkusExtensionName>
  </PropertyGroup>

  <Import Project="../../src/Ankus.Sdk/Ankus.Sdk.targets" />

</Project>
