<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Ankus</RootNamespace>
    <Description>Native AOT-compatible PostgreSQL extension APIs for .NET.</Description>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Formats.Cbor" />
    <InternalsVisibleTo Include="Ankus.Runtime.Tests" />
  </ItemGroup>
</Project>
