<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AnkusExtensionName>ankus_test</AnkusExtensionName>
  </PropertyGroup>
  <ItemGroup>
    <AdditionalFiles Include="Sql/*.sql" />
    <ProjectReference Include="../Ankus.SerializationContracts/Ankus.SerializationContracts.csproj" />
  </ItemGroup>
  <Import Project="../../src/Ankus.Sdk/Ankus.Sdk.targets" />
</Project>
