<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Query-tree Var manipulation through PostgreSQL's rewrite/rewriteManip.h functions.</Description>
    <AnkusExtensionName>ankus_rewrite_manip</AnkusExtensionName>
    <AnkusExtensionControlFile>$(MSBuildProjectDirectory)/ankus_rewrite_manip.control</AnkusExtensionControlFile>
  </PropertyGroup>

  <Import Project="../../src/Ankus.Sdk/Ankus.Sdk.targets" />

</Project>
