<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>pgrx's custom_libname example: a native library named independently of its project and extension.</Description>
    <AnkusLibraryName>other_name</AnkusLibraryName>
    <AnkusExtensionName>ankus_custom_libname</AnkusExtensionName>
    <AnkusExtensionControlFile>$(MSBuildProjectDirectory)/ankus_custom_libname.control</AnkusExtensionControlFile>
  </PropertyGroup>

  <Import Project="../../src/Ankus.Sdk/Ankus.Sdk.targets" />

</Project>
