using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ankus.Generators;

/// <summary>
/// Generates managed dispatchers, native PostgreSQL error boundaries, and SQL declarations for attributed functions.
/// </summary>
[Generator]
public sealed class PgFunctionGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor s_invalidFunction = new(
        "ANKUS001", "Unsupported PostgreSQL function",
        "'{0}' must be an accessible, non-generic static method returning int, with at most 100 by-value int parameters",
        "Ankus", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor s_invalidName = new(
        "ANKUS002", "Invalid PostgreSQL function name",
        "SQL function name '{0}' must be unique and contain 1-63 lowercase ASCII letters, digits, or underscores",
        "Ankus", DiagnosticSeverity.Error, isEnabledByDefault: true);

    /// <summary>
    /// Registers semantic attribute discovery and deterministic extension source generation.
    /// </summary>
    /// <param name="context">The incremental generation context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<IMethodSymbol> functions = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Ankus.PgFunctionAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (attributeContext, _) => (IMethodSymbol)attributeContext.TargetSymbol);
        context.RegisterSourceOutput(functions.Collect(), static (output, methods) => Generate(output, methods));
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<IMethodSymbol> methods)
    {
        if (methods.IsEmpty)
        {
            return;
        }

        var names = new HashSet<string>(StringComparer.Ordinal);
        var managed = new StringBuilder();
        var native = new StringBuilder("#include \"postgres.h\"\n#include \"fmgr.h\"\nPG_MODULE_MAGIC;\n");
        var sql = new StringBuilder();
        var exports = new StringBuilder("Pg_magic_func\n");
        managed.AppendLine("// <auto-generated />");
        managed.AppendLine("namespace Ankus.Generated;");
        managed.AppendLine("internal static unsafe class ExtensionDispatchers");
        managed.AppendLine("{");

        foreach (IMethodSymbol method in methods.OrderBy(static method => method.ToDisplayString(), StringComparer.Ordinal))
        {
            if (!IsSupported(method))
            {
                context.ReportDiagnostic(Diagnostic.Create(s_invalidFunction, method.Locations.FirstOrDefault(), method.Name));
                continue;
            }

            string name = GetSqlName(method);
            if (!IsValidName(name) || !names.Add(name))
            {
                context.ReportDiagnostic(Diagnostic.Create(s_invalidName, method.Locations.FirstOrDefault(), name));
                continue;
            }

            string nativeName = "ankus_fn_" + name;
            string callback = GetCallbackName(method, name);
            string count = method.Parameters.Length.ToString(CultureInfo.InvariantCulture);
            managed.AppendLine($"    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(EntryPoint = \"{callback}\")]");
            managed.AppendLine($"    private static int Invoke_{name}(int* arguments, int* result, byte* error, int capacity)");
            managed.AppendLine("    {");
            managed.AppendLine("        try");
            managed.AppendLine("        {");
            string arguments = string.Join(", ", Enumerable.Range(0, method.Parameters.Length).Select(
                static index => "arguments[" + index.ToString(CultureInfo.InvariantCulture) + "]"));
            string typeName = method.ContainingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            managed.AppendLine($"            *result = {typeName}.@{method.Name}({arguments});");
            managed.AppendLine("            return 0;");
            managed.AppendLine("        }");
            managed.AppendLine("        catch (global::System.Exception exception)");
            managed.AppendLine("        {");
            managed.AppendLine("            global::Ankus.NativeError.Write(exception, error, capacity);");
            managed.AppendLine("            return 1;");
            managed.AppendLine("        }");
            managed.AppendLine("    }");

            native.AppendLine($"extern int {callback}(const int32 *arguments, int32 *result, char *error, int capacity);");
            native.AppendLine($"PG_FUNCTION_INFO_V1({nativeName});");
            native.AppendLine($"PGDLLEXPORT Datum {nativeName}(PG_FUNCTION_ARGS)");
            native.AppendLine("{");
            string capacity = Math.Max(1, method.Parameters.Length).ToString(CultureInfo.InvariantCulture);
            native.AppendLine($"    int32 arguments[{capacity}] = {{0}};");
            native.AppendLine("    int32 result = 0;");
            native.AppendLine("    char error[2048] = {0};");
            native.AppendLine($"    if (PG_NARGS() != {count})");
            native.AppendLine("        ereport(ERROR, (errmsg(\"Incorrect argument count for generated Ankus function\")));");
            for (int index = 0; index < method.Parameters.Length; index++)
            {
                string argument = index.ToString(CultureInfo.InvariantCulture);
                native.AppendLine($"    if (PG_ARGISNULL({argument}))");
                native.AppendLine("    {");
                native.AppendLine("        PG_RETURN_NULL();");
                native.AppendLine("    }");
                native.AppendLine($"    arguments[{argument}] = PG_GETARG_INT32({argument});");
            }

            native.AppendLine($"    if ({callback}(arguments, &result, error, sizeof(error)) != 0)");
            native.AppendLine("    {");
            native.AppendLine("        ereport(ERROR, (errcode(ERRCODE_EXTERNAL_ROUTINE_EXCEPTION), errmsg_internal(\"%s\", error)));");
            native.AppendLine("    }");
            native.AppendLine("    PG_RETURN_INT32(result);");
            native.AppendLine("}");
            sql.AppendLine($"CREATE FUNCTION \"{name}\"({string.Join(", ", method.Parameters.Select(static _ => "integer"))})");
            sql.AppendLine($"RETURNS integer AS 'MODULE_PATHNAME', '{nativeName}' LANGUAGE c STRICT;");
            exports.AppendLine(nativeName);
            exports.AppendLine("pg_finfo_" + nativeName);
        }

        managed.AppendLine("}");
        context.AddSource("ExtensionDispatchers.g.cs", managed.ToString());
        string metadata = "// <auto-generated />\n" +
            Metadata("Ankus.NativeSource", native.ToString()) +
            Metadata("Ankus.Sql", sql.ToString()) +
            Metadata("Ankus.Exports", exports.ToString());
        context.AddSource("ExtensionManifest.g.cs", metadata);
    }

    private static string Metadata(string key, string value)
        => $"[assembly: global::System.Reflection.AssemblyMetadata(\"{key}\", {SymbolDisplay.FormatLiteral(value, quote: true)})]\n";

    private static bool IsSupported(IMethodSymbol method)
    {
        if (!method.IsStatic || method.IsGenericMethod || method.IsAbstract || method.ReturnsByRef || method.ReturnsByRefReadonly ||
            method.ReturnType.SpecialType != SpecialType.System_Int32 || method.Parameters.Length > 100 ||
            method.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal) ||
            method.Parameters.Any(static parameter => parameter.RefKind != RefKind.None ||
                parameter.Type.SpecialType != SpecialType.System_Int32))
        {
            return false;
        }

        for (INamedTypeSymbol? type = method.ContainingType; type is not null; type = type.ContainingType)
        {
            if (type.IsGenericType || type.IsFileLocal ||
                type.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
            {
                return false;
            }
        }

        return true;
    }

    private static string GetSqlName(IMethodSymbol method)
    {
        AttributeData attribute = method.GetAttributes().First(
            static attribute => attribute.AttributeClass?.ToDisplayString() == "Ankus.PgFunctionAttribute");
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
        {
            if (argument.Key == "Name" && argument.Value.Value is string value)
            {
                return value;
            }
        }

        var name = new StringBuilder();
        for (int index = 0; index < method.Name.Length; index++)
        {
            char current = method.Name[index];
            if (char.IsUpper(current) && index > 0 &&
                (char.IsLower(method.Name[index - 1]) ||
                 (index + 1 < method.Name.Length && char.IsLower(method.Name[index + 1]))))
            {
                name.Append('_');
            }

            name.Append(char.ToLowerInvariant(current));
        }

        return name.ToString();
    }

    private static bool IsValidName(string name)
        => name.Length is > 0 and <= 63 && name[0] is >= 'a' and <= 'z' or '_' &&
            name.All(static character => character is >= 'a' and <= 'z' or >= '0' and <= '9' or '_');

    private static string GetCallbackName(IMethodSymbol method, string sqlName)
    {
        string identity = method.ContainingAssembly.Identity + ":" + method.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        using SHA256 hash = SHA256.Create();
        byte[] bytes = hash.ComputeHash(Encoding.UTF8.GetBytes(identity));
        string suffix = string.Concat(bytes.Take(16).Select(static value => value.ToString("x2", CultureInfo.InvariantCulture)));
        return "ankus_managed_" + suffix + "_" + sqlName;
    }
}
