using System.Collections.Immutable;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ankus.Generators;

/// <summary>
/// Generates managed dispatchers, native PostgreSQL error boundaries, and SQL declarations for attributed functions.
/// </summary>
[Generator]
public sealed class PgFunctionGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor s_invalidFunction = new(
        "ANKUS001", "Unsupported PostgreSQL function",
        "'{0}' must be an accessible, synchronous, non-generic static method using supported SQL types and at most 100 by-value parameters",
        "Ankus", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor s_invalidName = new(
        "ANKUS002", "Invalid PostgreSQL function name",
        "SQL name '{0}' must contain 1-63 lowercase ASCII letters, digits, or underscores, and its SQL signature must be unique",
        "Ankus", DiagnosticSeverity.Error, isEnabledByDefault: true);

    /// <summary>
    /// Registers semantic attribute discovery and deterministic extension source generation.
    /// </summary>
    /// <param name="context">The incremental generation context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<IMethodSymbol> functions = context.SyntaxProvider.ForAttributeWithMetadataName(
            "Ankus.PgFunctionAttribute",
            static (node, _) => node is MethodDeclarationSyntax,
            static (attributeContext, _) => (IMethodSymbol)attributeContext.TargetSymbol);
        context.RegisterSourceOutput(functions.Collect(), static (output, methods) => Generate(output, methods));
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<IMethodSymbol> methods)
    {
        if (methods.IsEmpty)
        {
            return;
        }

        var names = new HashSet<string>(StringComparer.Ordinal);
        var managed = new StringBuilder();
        var native = new StringBuilder(NativeBridge.Source);
        native.AppendLine(NativeBridge.ReadBuffers);
        native.AppendLine(NativeBridge.WriteBuffer);
        native.AppendLine(NativeExtendedTypes.Source);
        native.AppendLine(NativeSpiBridge.Source);
        native.AppendLine(NativeCursorBridge.Source);
        native.AppendLine(NativeSessionBridge.Source);
        native.AppendLine(NativeErrorBridge.Source);
        native.AppendLine(GuardedBackend.Source);

        var sql = new StringBuilder();
        var exports = new StringBuilder("Pg_magic_func\n");
        managed.AppendLine("// <auto-generated />");
        managed.AppendLine("#nullable enable");
        managed.AppendLine("namespace Ankus.Generated;");
        managed.AppendLine("internal static unsafe class ExtensionDispatchers");
        managed.AppendLine("{");

        foreach (IMethodSymbol method in methods.OrderBy(static method => method.ToDisplayString(), StringComparer.Ordinal))
        {
            if (!IsSupported(method))
            {
                context.ReportDiagnostic(Diagnostic.Create(s_invalidFunction, method.Locations.FirstOrDefault(), method.Name));
                continue;
            }

            string name = GetSqlName(method);
            string signature = name + "(" + string.Join(",", method.Parameters.Select(
                static parameter => FunctionType.Create(parameter.Type)!.Sql)) + ")";
            if (!IsValidName(name) || !names.Add(signature))
            {
                context.ReportDiagnostic(Diagnostic.Create(s_invalidName, method.Locations.FirstOrDefault(), name));
                continue;
            }

            string callback = GetCallbackName(method, name);
            PgFunctionEmitter.Emit(method, name, callback, managed, native, sql, exports);
        }

        managed.AppendLine("}");
        context.AddSource("ExtensionDispatchers.g.cs", managed.ToString());
        string metadata = "// <auto-generated />\n" +
            Metadata("Ankus.NativeSource", native.ToString()) +
            Metadata("Ankus.Sql", sql.ToString()) +
            Metadata("Ankus.Exports", exports.ToString());
        context.AddSource("ExtensionManifest.g.cs", metadata);
    }

    private static string Metadata(string key, string value)
        => $"[assembly: global::System.Reflection.AssemblyMetadata(\"{key}\", {SymbolDisplay.FormatLiteral(value, quote: true)})]\n";

    private static bool IsSupported(IMethodSymbol method)
    {
        if (!method.IsStatic || method.IsAsync || method.IsGenericMethod || method.IsAbstract ||
            method.ReturnsByRef || method.ReturnsByRefReadonly ||
            FunctionType.Create(method.ReturnType) is null || method.Parameters.Length > 100 ||
            method.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal) ||
            method.Parameters.Any(static parameter => parameter.RefKind != RefKind.None ||
                FunctionType.Create(parameter.Type) is null))
        {
            return false;
        }

        for (INamedTypeSymbol? type = method.ContainingType; type is not null; type = type.ContainingType)
        {
            if (type.IsGenericType || type.IsFileLocal ||
                type.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal))
            {
                return false;
            }
        }

        return true;
    }

    private static string GetSqlName(IMethodSymbol method)
    {
        AttributeData attribute = method.GetAttributes().First(
            static attribute => attribute.AttributeClass?.ToDisplayString() == "Ankus.PgFunctionAttribute");
        foreach (KeyValuePair<string, TypedConstant> argument in attribute.NamedArguments)
        {
            if (argument.Key == "Name" && argument.Value.Value is string value)
            {
                return value;
            }
        }

        var name = new StringBuilder();
        for (int index = 0; index < method.Name.Length; index++)
        {
            char current = method.Name[index];
            if (char.IsUpper(current) && index > 0 &&
                (char.IsLower(method.Name[index - 1]) ||
                 (index + 1 < method.Name.Length && char.IsLower(method.Name[index + 1]))))
            {
                name.Append('_');
            }

            name.Append(char.ToLowerInvariant(current));
        }

        return name.ToString();
    }

    private static bool IsValidName(string name)
        => name.Length is > 0 and <= 63 && name[0] is >= 'a' and <= 'z' or '_' &&
            name.All(static character => character is >= 'a' and <= 'z' or >= '0' and <= '9' or '_');

    private static string GetCallbackName(IMethodSymbol method, string sqlName)
    {
        string identity = method.ContainingAssembly.Identity + ":" + method.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        using SHA256 hash = SHA256.Create();
        byte[] bytes = hash.ComputeHash(Encoding.UTF8.GetBytes(identity));
        string suffix = string.Concat(bytes.Take(16).Select(static value => value.ToString("x2", CultureInfo.InvariantCulture)));
        return "ankus_managed_" + suffix + "_" + sqlName;
    }
}
