using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Ankus.Generators;

/// <summary>
/// Emits lazily selected static callbacks with a managed exception boundary and exact native value transport.
/// </summary>
internal static class PgNativeCallbackEmitter
{
    /// <summary>
    /// Implements partial callback properties without exporting or rooting unused managed dispatchers.
    /// </summary>
    /// <param name="declarations">The validated properties and statically resolved handlers.</param>
    /// <returns>Complete partial declarations and imported native registration accessors.</returns>
    internal static string Emit(IEnumerable<NativeCallbackDeclaration> declarations)
    {
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        foreach (NativeCallbackDeclaration declaration in declarations)
        {
            IPropertySymbol property = declaration.Property;
            bool namespaced = !property.ContainingNamespace.IsGlobalNamespace;
            if (namespaced)
            {
                var parts = new Stack<string>();
                for (INamespaceSymbol space = property.ContainingNamespace; !space.IsGlobalNamespace; space = space.ContainingNamespace)
                {
                    parts.Push("@" + space.Name);
                }

                source.AppendLine("namespace " + string.Join(".", parts));
                source.AppendLine("{");
            }

            var containers = new Stack<INamedTypeSymbol>();
            for (INamedTypeSymbol? type = property.ContainingType; type is not null; type = type.ContainingType)
            {
                containers.Push(type);
            }

            foreach (INamedTypeSymbol type in containers)
            {
                string kind = type.TypeKind == TypeKind.Struct ? "struct" : "class";
                source.AppendLine($"{Access(type.DeclaredAccessibility)} {(type.IsStatic ? "static " : string.Empty)}unsafe partial " +
                    $"{(type.IsRecord ? "record " : string.Empty)}{kind} @{type.Name}");
                source.AppendLine("{");
            }

            string identity = declaration.Identity;
            string dispatcher = "AnkusDispatch_" + identity;
            string accessor = "AnkusCallback_" + identity;
            string managedType = Name(property.Type);
            bool hides = property.DeclaringSyntaxReferences.Any(static reference => reference.GetSyntax() is PropertyDeclarationSyntax syntax &&
                syntax.Modifiers.Any(SyntaxKind.NewKeyword));
            source.AppendLine($$"""
                {{Access(property.DeclaredAccessibility)}} {{(hides ? "new " : string.Empty)}}static partial {{managedType}} @{{property.Name}}
                {
                    get
                    {
                        global::Ankus.NativeRawCallback.ValidateBinding<{{managedType}}>();
                        nint address = {{accessor}}((nint)(delegate* unmanaged[Cdecl]<global::Ankus.NativeCallArgument*, nuint, nint, nuint, global::Ankus.NativeCallbackContext*, int>)&{{dispatcher}}.Invoke);
                        if (address == 0)
                        {
                            throw new global::System.InvalidOperationException("The native callback registration conflicts with an existing handler.");
                        }

                        return new {{managedType}}(address);
                    }
                }

                [global::System.Runtime.InteropServices.DllImport("Ankus.NativeBodies", EntryPoint = "ankus_native_callback_{{declaration.NativeSignature.ToString(CultureInfo.InvariantCulture)}}_{{identity}}",
                    ExactSpelling = true, CallingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl)]
                private static extern nint {{accessor}}(nint target);

                private static class {{dispatcher}}
                {
                [global::System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = [typeof(global::System.Runtime.CompilerServices.CallConvCdecl)])]
                internal static int Invoke(global::Ankus.NativeCallArgument* arguments, nuint count,
                    nint result, nuint resultSize, global::Ankus.NativeCallbackContext* context)
                {
                    if (context is null || context->Error == 0)
                    {
                        return 1;
                    }

                    nint previousBackend = global::Ankus.NativeBackend.Enter(context->Execute);
                    nint previousRead = global::Ankus.NativeGuc.Enter(context->Read);
                    nint previousLog = global::Ankus.NativeLog.Enter(context->Log);
                    nint previousMemory = 0;
                    bool memoryEntered = false;
                    try
                    {
                        previousMemory = global::Ankus.NativeMemoryContext.Enter(context->Memory);
                        memoryEntered = true;
                        global::Ankus.NativeRawCallback.ValidateBinding<{{managedType}}>();
                        global::Ankus.NativeRawCallback.ValidateFrame(arguments, count, {{declaration.Signature.Parameters.Length.ToString(CultureInfo.InvariantCulture)}},
                            result, resultSize, {{(declaration.Signature.ReturnsVoid ? "-1" : Size(declaration.Signature.ReturnType))}});
                """);
            var arguments = new List<string>();
            for (int index = 0; index < declaration.Signature.Parameters.Length; index++)
            {
                ITypeSymbol type = declaration.Signature.Parameters[index].Type;
                string number = index.ToString(CultureInfo.InvariantCulture);
                string argument = "argument" + number;
                string reader = NativeCallbackDeclaration.IsNativeValue(type) ? "ReadNative" : "Read";
                source.AppendLine($"        {Name(type)} {argument} = global::Ankus.NativeRawCallback.{reader}<{Name(type)}>(arguments[{number}]);");
                arguments.Add(argument);
            }

            string invocation = Name(declaration.Handler.ContainingType) + ".@" + declaration.Handler.Name + "(" + string.Join(", ", arguments) + ")";
            if (declaration.Signature.ReturnsVoid)
            {
                source.AppendLine("        " + invocation + ";");
            }
            else
            {
                ITypeSymbol resultType = declaration.Signature.ReturnType;
                string writer = NativeCallbackDeclaration.IsNativeValue(resultType) ? "WriteNative" : "Write";
                source.AppendLine($"        {Name(resultType)} value = {invocation};");
                source.AppendLine($"        global::Ankus.NativeRawCallback.{writer}(result, resultSize, value);");
            }

            source.AppendLine("""
                        return 0;
                    }
                    catch (global::System.Exception exception)
                    {
                        global::Ankus.NativeError.Write(exception, (global::Ankus.NativeCallError*)context->Error);
                        return 1;
                    }
                    finally
                    {
                        if (memoryEntered)
                        {
                            global::Ankus.NativeMemoryContext.Exit(previousMemory);
                        }

                        global::Ankus.NativeLog.Exit(previousLog);
                        global::Ankus.NativeGuc.Exit(previousRead);
                        global::Ankus.NativeBackend.Exit(previousBackend);
                    }
                }
                }

                """);
            foreach (INamedTypeSymbol _ in containers)
            {
                source.AppendLine("}");
            }

            if (namespaced)
            {
                source.AppendLine("}");
            }

            source.AppendLine();
        }

        return source.ToString();
    }

    private static string Name(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string Size(ITypeSymbol type) => NativeCallbackDeclaration.IsNativeValue(type)
        ? $"global::Ankus.NativeRawCallback.NativeSize<{Name(type)}>()" : $"sizeof({Name(type)})";

    private static string Access(Accessibility value) => value switch
    {
        Accessibility.Public => "public",
        Accessibility.Internal => "internal",
        Accessibility.Private => "private",
        Accessibility.Protected => "protected",
        Accessibility.ProtectedOrInternal => "protected internal",
        Accessibility.ProtectedAndInternal => "private protected",
        _ => throw new InvalidOperationException("A callback declaration requires explicit member accessibility."),
    };
}
