using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ankus.Generators;

/// <summary>
/// Renders portable source and dependency comments without changing a declaration's SQL body.
/// </summary>
internal static class SqlProvenance
{
    /// <summary>
    /// Identifies generated installation and selected scripts.
    /// </summary>
    internal const string Preamble = "-- Generated by Ankus. Do not edit.\n\n";

    /// <summary>
    /// Freezes only portable attribution and SQL values that affect one connected component's text.
    /// </summary>
    /// <param name="entity">The validated graph declaration.</param>
    /// <param name="projectDirectory">The root used for portable source attribution.</param>
    /// <returns>The immutable comment and SQL rendering contract.</returns>
    internal static Model Create(SqlEntity entity, string projectDirectory)
    {
        string sql = entity.SqlTemplate;
        if (sql.Length == 0)
        {
            return new(sql, null, null, new EquatableArray<string>([]), null, new EquatableArray<string>([]));
        }

        Origin? origin = null;
        if (entity.Location is { Kind: LocationKind.SourceFile or LocationKind.ExternalFile } location)
        {
            FileLinePositionSpan span = location.GetLineSpan();
            if (span.Path.Length != 0)
            {
                origin = new(RelativePath(span.Path, projectDirectory), span.StartLinePosition.Line + 1);
            }
        }

        IEnumerable<string> sources = entity.ManagedSources.Count != 0 ? entity.ManagedSources : entity.Owner?.ManagedSources ?? [];
        string[] names = [.. sources.OrderBy(static name => name, StringComparer.Ordinal)];
        return new(sql, origin, entity.SourceFile is { } file ? RelativePath(file, projectDirectory) : null,
            new(names.Length == 0 ? [entity.DisplayName] : names), entity.Owner?.DisplayName,
            new(entity.Dependencies.OrderBy(static dependency => dependency.Key, StringComparer.Ordinal).Select(static dependency => dependency.DisplayName)));
    }

    /// <summary>
    /// Renders one acyclic graph component only after its SQL or provenance contract changes.
    /// </summary>
    /// <param name="model">The detached SQL and portable source/dependency comments.</param>
    /// <returns>The complete connected component with typed schema markers retained.</returns>
    internal static string Render(Model model)
    {
        if (model.Sql.Length == 0)
        {
            return string.Empty;
        }

        var text = new StringBuilder("/* <begin connected objects> */\n");
        if (model.Source is { } origin)
        {
            text.Append("-- ").Append(Escape(origin.Path)).Append(':')
                .Append(origin.Line.ToString(CultureInfo.InvariantCulture)).Append('\n');
        }

        foreach (string name in model.ManagedSources)
        {
            text.Append("-- ").Append(Escape(name)).Append('\n');
        }

        if (model.SourceFile is { } file)
        {
            text.Append("-- SQL file: ").Append(Escape(file)).Append('\n');
        }

        if (model.Owner is { } owner)
        {
            text.Append("-- member of: ").Append(Escape(owner)).Append('\n');
        }

        if (model.Dependencies.Count != 0)
        {
            text.Append("-- requires:\n");
            foreach (string dependency in model.Dependencies)
            {
                text.Append("--   ").Append(Escape(dependency)).Append('\n');
            }
        }

        text.Append('\n').Append(model.Sql);
        if (model.Sql[model.Sql.Length - 1] != '\n')
        {
            text.Append('\n');
        }

        return text.Append("/* </end connected objects> */\n\n").ToString();
    }

    /// <summary>
    /// Contains exactly the SQL and comment values used by one connected component.
    /// </summary>
    /// <param name="Sql">The complete SQL template.</param>
    /// <param name="Source">The portable physical declaration origin, when present.</param>
    /// <param name="SourceFile">The portable additional SQL file, when present.</param>
    /// <param name="ManagedSources">The ordered managed declaration labels.</param>
    /// <param name="Owner">The owning declaration label, when present.</param>
    /// <param name="Dependencies">The dependency labels in key order.</param>
    internal sealed record Model(string Sql, Origin? Source, string? SourceFile, EquatableArray<string> ManagedSources,
        string? Owner, EquatableArray<string> Dependencies);

    /// <summary>
    /// Retains portable physical source attribution independently of compiler coordinates.
    /// </summary>
    /// <param name="Path">The portable file label.</param>
    /// <param name="Line">The one-based physical source line.</param>
    internal sealed record Origin(string Path, int Line);

    /// <summary>
    /// Removes machine-specific roots using lexical paths, including Windows inputs on other hosts.
    /// </summary>
    private static string RelativePath(string path, string projectDirectory)
    {
        string normalized = Normalize(path);
        if (RootLength(normalized) != 0)
        {
            string project = Normalize(projectDirectory).TrimEnd('/') + "/";
            StringComparison comparison = project.StartsWith("//", StringComparison.Ordinal) || project.Length > 1 && project[1] == ':'
                ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
            if (RootLength(projectDirectory.Replace('\\', '/')) != 0 && normalized.StartsWith(project, comparison))
            {
                return normalized.Substring(project.Length);
            }

            return normalized.Substring(normalized.LastIndexOf('/') + 1);
        }

        return normalized.StartsWith("../", StringComparison.Ordinal) ? normalized.Substring(normalized.LastIndexOf('/') + 1) : normalized;
    }

    /// <summary>
    /// Normalizes separators and dot segments without resolving filesystem links or touching the filesystem.
    /// </summary>
    private static string Normalize(string path)
    {
        path = path.Replace('\\', '/');
        int root = RootLength(path);
        var parts = new List<string>();
        foreach (string part in path.Substring(root).Split(['/'], StringSplitOptions.RemoveEmptyEntries))
        {
            if (part == ".")
            {
                continue;
            }

            if (part == ".." && parts.Count != 0 && parts[parts.Count - 1] != "..")
            {
                parts.RemoveAt(parts.Count - 1);
            }
            else if (part != ".." || root == 0)
            {
                parts.Add(part);
            }
        }

        return path.Substring(0, root) + string.Join("/", parts);
    }

    /// <summary>
    /// Recognizes Unix, drive and UNC roots independently of the compiler host.
    /// </summary>
    private static int RootLength(string path)
        => path.StartsWith("//", StringComparison.Ordinal) ? 2 : path.StartsWith("/", StringComparison.Ordinal) ? 1 :
            path.Length >= 3 && path[1] == ':' && path[2] == '/' ? 3 : 0;

    /// <summary>
    /// Keeps user-controlled labels within one unambiguous SQL line comment.
    /// </summary>
    private static string Escape(string value)
    {
        var text = new StringBuilder();
        for (int index = 0; index < value.Length; index++)
        {
            char character = value[index];
            if (char.IsHighSurrogate(character) && index + 1 < value.Length && char.IsLowSurrogate(value[index + 1]))
            {
                text.Append(character).Append(value[++index]);
            }
            else if (char.IsControl(character) || char.IsSurrogate(character) || character is '\u2028' or '\u2029')
            {
                text.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
            }
            else
            {
                text.Append(character == '\\' ? "\\\\" : character.ToString());
            }
        }

        return text.ToString();
    }
}
