using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Ankus.Generators;

/// <summary>
/// Renders portable source and dependency comments without changing a declaration's SQL body.
/// </summary>
internal static class SqlProvenance
{
    /// <summary>
    /// Identifies generated installation and selected scripts.
    /// </summary>
    internal const string Preamble = "-- Generated by Ankus. Do not edit.\n\n";

    /// <summary>
    /// Renders one acyclic graph component, retaining schema insertion markers for artifact consumers.
    /// </summary>
    internal static string Render(SqlEntity entity, string projectDirectory)
    {
        string sql = entity.SqlTemplate;
        if (sql.Length == 0)
        {
            return string.Empty;
        }

        var text = new StringBuilder("/* <begin connected objects> */\n");
        if (entity.Location is { IsInSource: true } location)
        {
            FileLinePositionSpan span = location.GetLineSpan();
            if (span.Path.Length != 0)
            {
                text.Append("-- ").Append(Escape(RelativePath(span.Path, projectDirectory))).Append(':')
                    .Append((span.StartLinePosition.Line + 1).ToString(CultureInfo.InvariantCulture)).Append('\n');
            }
        }

        IEnumerable<string> sources = entity.ManagedSources.Count != 0 ? entity.ManagedSources : entity.Owner?.ManagedSources ?? [];
        string[] names = [.. sources.OrderBy(static name => name, StringComparer.Ordinal)];
        foreach (string name in names.Length == 0 ? [entity.DisplayName] : names)
        {
            text.Append("-- ").Append(Escape(name)).Append('\n');
        }

        if (entity.SourceFile is { } file)
        {
            text.Append("-- SQL file: ").Append(Escape(RelativePath(file, projectDirectory))).Append('\n');
        }

        if (entity.Owner is { } owner)
        {
            text.Append("-- member of: ").Append(Escape(owner.DisplayName)).Append('\n');
        }

        if (entity.Dependencies.Count != 0)
        {
            text.Append("-- requires:\n");
            foreach (SqlEntity dependency in entity.Dependencies.OrderBy(static dependency => dependency.Key, StringComparer.Ordinal))
            {
                text.Append("--   ").Append(Escape(dependency.DisplayName)).Append('\n');
            }
        }

        text.Append('\n').Append(sql);
        if (sql[sql.Length - 1] != '\n')
        {
            text.Append('\n');
        }

        return text.Append("/* </end connected objects> */\n\n").ToString();
    }

    /// <summary>
    /// Removes machine-specific roots using lexical paths, including Windows inputs on other hosts.
    /// </summary>
    private static string RelativePath(string path, string projectDirectory)
    {
        string normalized = Normalize(path);
        if (RootLength(normalized) != 0)
        {
            string project = Normalize(projectDirectory).TrimEnd('/') + "/";
            StringComparison comparison = project.StartsWith("//", StringComparison.Ordinal) || project.Length > 1 && project[1] == ':'
                ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal;
            if (RootLength(projectDirectory.Replace('\\', '/')) != 0 && normalized.StartsWith(project, comparison))
            {
                return normalized.Substring(project.Length);
            }

            return normalized.Substring(normalized.LastIndexOf('/') + 1);
        }

        return normalized.StartsWith("../", StringComparison.Ordinal) ? normalized.Substring(normalized.LastIndexOf('/') + 1) : normalized;
    }

    /// <summary>
    /// Normalizes separators and dot segments without resolving filesystem links or touching the filesystem.
    /// </summary>
    private static string Normalize(string path)
    {
        path = path.Replace('\\', '/');
        int root = RootLength(path);
        var parts = new List<string>();
        foreach (string part in path.Substring(root).Split(['/'], StringSplitOptions.RemoveEmptyEntries))
        {
            if (part == ".")
            {
                continue;
            }

            if (part == ".." && parts.Count != 0 && parts[parts.Count - 1] != "..")
            {
                parts.RemoveAt(parts.Count - 1);
            }
            else if (part != ".." || root == 0)
            {
                parts.Add(part);
            }
        }

        return path.Substring(0, root) + string.Join("/", parts);
    }

    /// <summary>
    /// Recognizes Unix, drive and UNC roots independently of the compiler host.
    /// </summary>
    private static int RootLength(string path)
        => path.StartsWith("//", StringComparison.Ordinal) ? 2 : path.StartsWith("/", StringComparison.Ordinal) ? 1 :
            path.Length >= 3 && path[1] == ':' && path[2] == '/' ? 3 : 0;

    /// <summary>
    /// Keeps user-controlled labels within one unambiguous SQL line comment.
    /// </summary>
    private static string Escape(string value)
    {
        var text = new StringBuilder();
        for (int index = 0; index < value.Length; index++)
        {
            char character = value[index];
            if (char.IsHighSurrogate(character) && index + 1 < value.Length && char.IsLowSurrogate(value[index + 1]))
            {
                text.Append(character).Append(value[++index]);
            }
            else if (char.IsControl(character) || char.IsSurrogate(character) || character is '\u2028' or '\u2029')
            {
                text.Append("\\u").Append(((int)character).ToString("x4", CultureInfo.InvariantCulture));
            }
            else
            {
                text.Append(character == '\\' ? "\\\\" : character.ToString());
            }
        }

        return text.ToString();
    }
}
