using System.Collections.Immutable;
using Ankus.PgConfig;
using Microsoft.CodeAnalysis;

namespace Ankus.Generators.Tests;

public sealed partial class PgFunctionGeneratorTests
{
    /// <summary>
    /// Installation and embedded fragments retain exact source, managed identity and resolved prerequisites.
    /// </summary>
    [TestMethod]
    public void SqlProvenanceRetainsLocationsNamesAndDependencies()
    {
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            [assembly: Ankus.PgSql("seed", "SELECT 1;")]
            namespace Demo;
            public static class Queries
            {
                [Ankus.PgFunction(Requires = ["seed"])]
                public static int Answer() => 42;
            }
            """, options: new SqlOptions("/build/project"), path: "/build/project/functions/Queries.cs");
        Assert.IsEmpty(diagnostics);
        Assert.IsEmpty(compilation.GetDiagnostics(context.CancellationToken).Where(static value => value.Severity == DiagnosticSeverity.Error));
        string sql = ManifestValue(compilation, "Ankus.Sql");
        Assert.StartsWith("-- Generated by Ankus. Do not edit.\n\n", sql);
        Assert.Contains("/* <begin connected objects> */\n-- functions/Queries.cs:6\n-- Demo.Queries.Answer()\n-- requires:\n--   seed\n\n", sql);
        Assert.DoesNotContain("/build/project", sql);
        ExtensionSchemaGraph graph = ExtensionSchemaGraph.Parse(ManifestValue(compilation, "Ankus.SqlGraph"));
        Assert.AreEqual(sql, graph.Sql);
        Assert.AreSequenceEqual(["sql", "function"], graph.Items.Select(static item => item.Kind));
        Assert.AreEqual("/* <begin connected objects> */\n-- functions/Queries.cs:1\n-- seed\n\nSELECT 1;\n/* </end connected objects> */\n\n", graph.Items[0].Sql);
        Assert.EndsWith("/* </end connected objects> */\n\n", graph.Items[1].Sql);
    }

    /// <summary>
    /// Paths remain portable and cannot expose build-machine roots or inject executable lines.
    /// </summary>
    /// <param name="project">The compiler-visible project root.</param>
    /// <param name="path">The physical syntax tree path.</param>
    /// <param name="expected">The exact portable source comment.</param>
    [TestMethod]
    [DataRow("/build/project", "/build/project/nested/../src/Queries.cs", "src/Queries.cs")]
    [DataRow("C:\\build\\project", "c:/BUILD/project/src/Queries.cs", "src/Queries.cs")]
    [DataRow("\\\\build\\share\\project", "//BUILD/share/project/src/Queries.cs", "src/Queries.cs")]
    [DataRow("/build/project", "/private/person/Linked.cs", "Linked.cs")]
    [DataRow("/build/project", "/build/project-neighbor/Linked.cs", "Linked.cs")]
    [DataRow("/build/project", "../private/Linked.cs", "Linked.cs")]
    [DataRow("", "/private/person/Queries.cs", "Queries.cs")]
    [DataRow("/build/project", "src/Queries.cs", "src/Queries.cs")]
    [DataRow("/build/project", "src/café 🐘.cs", "src/café 🐘.cs")]
    [DataRow("/build/project", "src/zero\0\ud800.cs", "src/zero\\u0000\\ud800.cs")]
    [DataRow("/build/project", "src/evil\nSELECT 99;\r\u2028\u2029.cs", "src/evil\\u000aSELECT 99;\\u000d\\u2028\\u2029.cs")]
    public void SqlProvenanceNormalizesAndEscapesPaths(string project, string path, string expected)
    {
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            [assembly: Ankus.PgSql("seed", "SELECT 1;")]
            """, options: new SqlOptions(project), path: path);
        Assert.IsEmpty(diagnostics);
        Assert.AreEqual("-- Generated by Ankus. Do not edit.\n\n/* <begin connected objects> */\n-- " + expected +
            ":1\n-- seed\n\nSELECT 1;\n/* </end connected objects> */\n\n", ManifestValue(compilation, "Ankus.Sql"));
    }

    /// <summary>
    /// Dependency names with line breaks remain comments and preserve the authored SQL exactly.
    /// </summary>
    [TestMethod]
    public void SqlProvenanceEscapesDependencyLabelsWithoutChangingSql()
    {
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            [assembly: Ankus.PgSql("seed\nSELECT 99;", "SELECT $$line\n-- literal$$; -- tail")]
            [assembly: Ankus.PgSql("consumer", "SELECT 2;", Requires = ["seed\nSELECT 99;"])]
            """);
        Assert.IsEmpty(diagnostics);
        string sql = ManifestValue(compilation, "Ankus.Sql");
        Assert.Contains("-- seed\\u000aSELECT 99;\n\nSELECT $$line\n-- literal$$; -- tail\n/* </end connected objects> */", sql);
        Assert.Contains("-- requires:\n--   seed\\u000aSELECT 99;\n\nSELECT 2;", sql);
        Assert.DoesNotContain("\nSELECT 99;", sql);
        Assert.AreEqual(sql, ExtensionSchemaGraph.Parse(ManifestValue(compilation, "Ankus.SqlGraph")).Sql);
    }

    /// <summary>
    /// SQL files report their own origin as well as their C# declaration without altering the file body.
    /// </summary>
    [TestMethod]
    public void SqlProvenanceRetainsTrackedSqlFileOrigin()
    {
        string project = Path.Combine(AppContext.BaseDirectory, "virtual-project");
        var file = new SqlInput(Path.Combine(project, "sql", "seed.sql"), "SELECT 'café'; -- exact\n");
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            [assembly: Ankus.PgSqlFile("seed", "sql/seed.sql")]
            """, [file], new SqlOptions(project), Path.Combine(project, "Declarations.cs"));
        Assert.IsEmpty(diagnostics);
        Assert.Contains("-- Declarations.cs:1\n-- seed\n-- SQL file: sql/seed.sql\n\nSELECT 'café'; -- exact\n/* </end connected objects> */",
            ManifestValue(compilation, "Ankus.Sql"));
    }

    /// <summary>
    /// Shared schemas list their contributing declarations while generated family members retain their owner.
    /// </summary>
    [TestMethod]
    public void SqlProvenanceRetainsSharedAndDerivedOrigins()
    {
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            [Ankus.PgSchema("shared")] public static class A;
            [Ankus.PgSchema("shared")] public static class B;
            [Ankus.PgEnum, Ankus.PgEquality] public enum Choice { A, B }
            """, path: "Declarations.cs");
        Assert.IsEmpty(diagnostics);
        ExtensionSchemaGraph graph = ExtensionSchemaGraph.Parse(ManifestValue(compilation, "Ankus.SqlGraph"));
        ExtensionSchemaItem schema = graph.Items.Single(static item => item.Kind == "schema");
        Assert.Contains("-- Declarations.cs:1\n-- A\n-- B\n\nCREATE SCHEMA", schema.Sql);
        ExtensionSchemaItem member = graph.Items.First(static item => item.Owner.Length != 0);
        Assert.Contains("-- Declarations.cs:3\n-- Choice\n-- member of: ", member.Sql);
        Assert.Contains("-- requires:\n", member.Sql);
        Assert.AreEqual(ManifestValue(compilation, "Ankus.Sql"), graph.Sql);
    }

    /// <summary>
    /// Physical source locations stay truthful when C# line mapping names another file.
    /// </summary>
    [TestMethod]
    public void SqlProvenanceUsesPhysicalSourceLocations()
    {
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            #line 100 "/private/someone/Mapped.cs"
            [assembly: Ankus.PgSql("seed", "SELECT 1;")]
            """, path: "Declarations.cs");
        Assert.IsEmpty(diagnostics);
        string sql = ManifestValue(compilation, "Ankus.Sql");
        Assert.Contains("-- Declarations.cs:2\n", sql);
        Assert.DoesNotContain("Mapped.cs", sql);
        Assert.DoesNotContain("/private", sql);
    }

    /// <summary>
    /// Suppressed families stay empty and a replacement retains one annotated body with all graph identities.
    /// </summary>
    /// <param name="replace">Whether the function supplies replacement SQL instead of disabling it.</param>
    [TestMethod]
    [DataRow(false)]
    [DataRow(true)]
    public void SqlProvenancePreservesSuppressionAndReplacement(bool replace)
    {
        string policy = replace ? "Sql = \"SELECT 'replacement';\"" : "GenerateSql = false";
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate($$"""
            public static class Functions
            {
                [Ankus.PgFunction({{policy}}), Ankus.PgOperator("===")]
                public static bool Equal(int left, int right) => left == right;
            }
            """, path: "Functions.cs");
        Assert.IsEmpty(diagnostics);
        ExtensionSchemaGraph graph = ExtensionSchemaGraph.Parse(ManifestValue(compilation, "Ankus.SqlGraph"));
        Assert.HasCount(2, graph.Items);
        Assert.IsEmpty(graph.Items[1].Sql);
        Assert.AreEqual(graph.Items[0].Id, graph.Items[1].Owner);
        Assert.AreEqual(replace ? "-- Generated by Ankus. Do not edit.\n\n/* <begin connected objects> */\n-- Functions.cs:4\n" +
            "-- Functions.Equal(int, int)\n\nSELECT 'replacement';\n/* </end connected objects> */\n\n" :
            "-- Generated by Ankus. Do not edit.\n\n-- No installable objects declared.\n", graph.Sql);
        Assert.AreEqual(ManifestValue(compilation, "Ankus.Sql"), graph.Sql);
    }

    /// <summary>
    /// Equivalent source trees in different checkout roots emit byte-identical SQL and graph metadata.
    /// </summary>
    [TestMethod]
    public void SqlProvenanceIsDeterministicAcrossCheckoutRoots()
    {
        const string Source = """
            [assembly: Ankus.PgSql("z", "SELECT 2;", Requires = ["a"])]
            [assembly: Ankus.PgSql("a", "SELECT 1;")]
            """;
        (Compilation first, ImmutableArray<Diagnostic> firstErrors) = Generate(Source,
            options: new SqlOptions("/private/first/project"), path: "/private/first/project/Schema.cs");
        (Compilation second, ImmutableArray<Diagnostic> secondErrors) = Generate(Source,
            options: new SqlOptions("D:\\different\\project"), path: "D:\\different\\project\\Schema.cs");
        Assert.IsEmpty(firstErrors);
        Assert.IsEmpty(secondErrors);
        Assert.AreEqual(ManifestValue(first, "Ankus.Sql"), ManifestValue(second, "Ankus.Sql"));
        Assert.AreEqual(ManifestValue(first, "Ankus.SqlGraph"), ManifestValue(second, "Ankus.SqlGraph"));
        Assert.AreEqual("-- Generated by Ankus. Do not edit.\n\n" +
            "/* <begin connected objects> */\n-- Schema.cs:2\n-- a\n\nSELECT 1;\n/* </end connected objects> */\n\n" +
            "/* <begin connected objects> */\n-- Schema.cs:1\n-- z\n-- requires:\n--   a\n\nSELECT 2;\n/* </end connected objects> */\n\n",
            ManifestValue(first, "Ankus.Sql"));
    }

    /// <summary>
    /// Authored comments and marker-shaped quoted text are retained, including leading blank lines and comments.
    /// </summary>
    [TestMethod]
    public void SqlProvenancePreservesAuthoredCommentsAndMarkerText()
    {
        (Compilation compilation, ImmutableArray<Diagnostic> diagnostics) = Generate("""
            [assembly: Ankus.PgSql("seed", "-- author's comment\n\nSELECT $$/* </end connected objects> */\n-- text$$; -- trailing")]
            """);
        Assert.IsEmpty(diagnostics);
        const string Body = "-- author's comment\n\nSELECT $$/* </end connected objects> */\n-- text$$; -- trailing\n";
        Assert.AreEqual(Body, Assert.ContainsSingle(DeclarationBodies(compilation)));
        Assert.AreEqual("-- Generated by Ankus. Do not edit.\n\n/* <begin connected objects> */\n-- seed\n\n" +
            Body + "/* </end connected objects> */\n\n", ManifestValue(compilation, "Ankus.Sql"));
    }
}
