<Project>
  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <NativeLib>Shared</NativeLib>
    <UseCurrentRuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and '$(UseCurrentRuntimeIdentifier)' == ''">true</UseCurrentRuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <AnkusPostgresMajor Condition="'$(AnkusPostgresMajor)' == ''">18</AnkusPostgresMajor>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
    <AnkusUpgradeScript Include="sql/$(AnkusExtensionName)--*--*.sql"
                        Condition="'$(EnableDefaultAnkusUpgradeScripts)' != 'false' and '$(AnkusExtensionName)' != ''" />
    <AnkusUpgradeScript Include="sql/$(TargetName.ToLowerInvariant().Replace('.', '_'))--*--*.sql"
                        Condition="'$(EnableDefaultAnkusUpgradeScripts)' != 'false' and '$(AnkusExtensionName)' == ''" />
  </ItemGroup>
</Project>
