<Project>
  <PropertyGroup>
    <UsingAnkusSdk>true</UsingAnkusSdk>
    <_AnkusNativeEnvironment Condition="'$(ANKUS_HOME)' != ''">ANKUS_HOME=$([MSBuild]::Escape($([MSBuild]::NormalizePath('$(MSBuildStartupDirectory)', '$(ANKUS_HOME)'))))</_AnkusNativeEnvironment>
    <PublishAot>true</PublishAot>
    <IsAotCompatible>true</IsAotCompatible>
    <NativeLib>Shared</NativeLib>
    <UseCurrentRuntimeIdentifier Condition="'$(RuntimeIdentifier)' == '' and '$(UseCurrentRuntimeIdentifier)' == ''">true</UseCurrentRuntimeIdentifier>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <AnkusPostgresMajor Condition="'$(AnkusPostgresMajor)' == ''">18</AnkusPostgresMajor>
    <AnkusReuseSchema Condition="'$(AnkusReuseSchema)' == ''">false</AnkusReuseSchema>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
    <CompilerVisibleProperty Include="AnkusIncludeTests" />
    <CompilerVisibleProperty Include="AnkusIncludeBenchmarks" />
    <CompilerVisibleProperty Include="Version" />
    <AnkusUpgradeScript Include="sql/$(AnkusExtensionName)--*--*.sql"
                        Condition="'$(EnableDefaultAnkusUpgradeScripts)' != 'false' and '$(AnkusExtensionName)' != ''" />
    <AnkusUpgradeScript Include="sql/$(TargetName.ToLowerInvariant().Replace('.', '_'))--*--*.sql"
                        Condition="'$(EnableDefaultAnkusUpgradeScripts)' != 'false' and '$(AnkusExtensionName)' == ''" />
    <AnkusVersionControlFile Include="sql/$(AnkusExtensionName)--*.control"
                             Condition="'$(EnableDefaultAnkusVersionControlFiles)' != 'false' and '$(AnkusExtensionName)' != ''" />
    <AnkusVersionControlFile Include="sql/$(TargetName.ToLowerInvariant().Replace('.', '_'))--*.control"
                             Condition="'$(EnableDefaultAnkusVersionControlFiles)' != 'false' and '$(AnkusExtensionName)' == ''" />
  </ItemGroup>
</Project>
