<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Ankus.PgConfig/Ankus.PgConfig.csproj" />
    <EmbeddedResource Include="Bindings/*.json;Bindings/*.h" />
    <None Update="Bindings/LICENSE.pgrx" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
