using System.Globalization;
using System.Numerics;
using System.Security.Cryptography;
using System.Text;

namespace Ankus.Build;

/// <summary>
/// Emits complete unmanaged node values from selected-header layout observations.
/// </summary>
internal static class NativeBindingCSharp
{
    /// <summary>
    /// Generates deterministic declarations whose identity changes with their native or managed contract.
    /// </summary>
    /// <param name="catalog">The pinned native declarations and cast graph.</param>
    /// <param name="layout">The validated observations from the selected headers.</param>
    /// <returns>The generated source and ABI-specific companion assembly identity.</returns>
    internal static NativeBindingSource Generate(NativeBindingCatalog catalog, NativeBindingLayout layout)
        => new Writer(catalog, layout).Generate();

    private sealed class Writer(NativeBindingCatalog catalog, NativeBindingLayout layout)
    {
        private const string IdentityMarker = "__ANKUS_BINDING_IDENTITY__";
        private readonly SortedSet<string> _enums = new(StringComparer.Ordinal);
        private readonly Dictionary<(string Element, int Count), string> _arrays = [];

        /// <summary>
        /// Emits the complete companion source and its content identity.
        /// </summary>
        /// <returns>The stable assembly contract.</returns>
        internal NativeBindingSource Generate()
        {
            var source = new StringBuilder("// <auto-generated/>\n#nullable enable\nnamespace Ankus.Postgres;\n\n");
            source.AppendLine("/// <summary>");
            source.AppendLine("/// Identifies the exact generated native binding contract.");
            source.AppendLine("/// </summary>");
            source.AppendLine("public static class NativeBinding");
            source.AppendLine("{");
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Gets the identity of these measured declarations.");
            source.AppendLine("    /// </summary>");
            source.AppendLine(CultureInfo.InvariantCulture, $"    public const string Identity = \"{IdentityMarker}\";");
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Identifies the operating-system and processor ABI measured by the native compiler.");
            source.AppendLine("    /// </summary>");
            source.AppendLine(CultureInfo.InvariantCulture, $"    public const string RuntimeIdentifier = \"{layout.RuntimeIdentifier}\";");
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Encodes measured concrete node tag sizes and alignments for the native boundary.");
            source.AppendLine("    /// </summary>");
            source.AppendLine(CultureInfo.InvariantCulture, $"    public const string NodeLayouts = \"{NativeBindingNodeLayouts.Encode(catalog, layout)}\";");
            source.AppendLine("    /// <summary>");
            source.AppendLine("    /// Rejects host primitive representations incompatible with these measured declarations.");
            source.AppendLine("    /// </summary>");
            source.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
            source.AppendLine("    internal static void ValidateHost()");
            source.AppendLine("    {");
            source.AppendLine(CultureInfo.InvariantCulture,
                $"        if (global::System.IntPtr.Size != {layout.PointerSize} || global::System.BitConverter.IsLittleEndian != {(layout.IsLittleEndian ? "true" : "false")} || global::System.Runtime.InteropServices.RuntimeInformation.RuntimeIdentifier != RuntimeIdentifier)");
            source.AppendLine("        {");
            source.AppendLine("            throw new global::System.PlatformNotSupportedException(\"The generated PostgreSQL bindings require their measured target ABI, pointer width and byte order.\");");
            source.AppendLine("        }");
            source.AppendLine("    }");
            source.AppendLine("}");
            source.AppendLine();
            WriteEnum(source, "NodeTag", new("uint", 4), catalog.Tags.ToDictionary(
                static tag => tag.Key, static tag => tag.Value.ToString(CultureInfo.InvariantCulture), StringComparer.Ordinal));

            foreach (NativeBindingSelectionEntry entry in NativeBindingSelection.Create(catalog))
            {
                WriteType(source, entry.Type, layout.Types[entry.Type.Name]);
            }

            foreach (string name in _enums)
            {
                NativeBindingEnum declaration = catalog.Enums[name];
                WriteEnum(source, name, EnumStorage(name), declaration.Values.ToDictionary(
                    static pair => pair.Key,
                    pair => NativeBindingEnums.NativeValue(pair.Value, layout.Enums[name]).ToString(CultureInfo.InvariantCulture),
                    StringComparer.Ordinal));
            }

            foreach (((string element, int count), string name) in _arrays)
            {
                source.AppendLine("/// <summary>");
                source.AppendLine(CultureInfo.InvariantCulture, $"/// Stores {count} contiguous native array elements.");
                source.AppendLine("/// </summary>");
                source.AppendLine(CultureInfo.InvariantCulture, $"[global::System.Runtime.CompilerServices.InlineArray({count})]");
                source.AppendLine(CultureInfo.InvariantCulture, $"public struct {name}");
                source.AppendLine("{");
                source.AppendLine(CultureInfo.InvariantCulture, $"    private {element} _element0;");
                source.AppendLine("}");
                source.AppendLine();
            }

            string body = source.ToString().ReplaceLineEndings("\n");
            string identity = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(body)));
            return new($"Ankus.Postgres.Pg{catalog.PostgresMajor}.{identity}", identity,
                body.Replace(IdentityMarker, identity, StringComparison.Ordinal));
        }

        private void WriteType(StringBuilder source, NativeBindingType type, NativeBindingTypeLayout native)
        {
            source.AppendLine("/// <summary>");
            source.AppendLine(CultureInfo.InvariantCulture, $"/// Represents the selected PostgreSQL {type.Name} native value. Pointer fields retain borrowed addresses.");
            source.AppendLine("/// </summary>");
            source.AppendLine(CultureInfo.InvariantCulture,
                $"[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = {native.Size}, Pack = {native.Alignment})]");
            source.AppendLine(CultureInfo.InvariantCulture, $"public struct @{type.Name} : global::Ankus.{(type.IsNode ? "IPgNativeNode" : "IPgNativeType")}");
            source.AppendLine("{");
            source.AppendLine(CultureInfo.InvariantCulture, $"    static int global::Ankus.IPgNativeType.PostgresMajor => {catalog.PostgresMajor};");
            source.AppendLine("    static string global::Ankus.IPgNativeType.AbiIdentity => NativeBinding.Identity;");
            source.AppendLine("    static string global::Ankus.IPgNativeType.RuntimeIdentifier => NativeBinding.RuntimeIdentifier;");
            source.AppendLine(CultureInfo.InvariantCulture, $"    static int global::Ankus.IPgNativeType.NativeSize => {native.Size};");
            source.AppendLine(CultureInfo.InvariantCulture, $"    static int global::Ankus.IPgNativeType.NativeAlignment => {native.Alignment};");
            if (type.IsNode)
            {
                string predicate = type.Name == "Node" ? "true" : type.CastTags.Count == 0 ? "false" :
                    "tag is " + string.Join(" or ", type.CastTags.Select(tag => catalog.Tags[tag].ToString(CultureInfo.InvariantCulture) + "U"));
                source.AppendLine(CultureInfo.InvariantCulture, $"    static bool global::Ankus.IPgNativeNode.AcceptsTag(uint tag) => {predicate};");
            }

            foreach (NativeBindingField field in type.Fields)
            {
                NativeBindingFieldLayout observed = native.Fields[field.Name];
                string representation = NativeBindingSelection.ResolveAlias(catalog, field.Representation);
                source.AppendLine();
                source.AppendLine("    /// <summary>");
                source.AppendLine(CultureInfo.InvariantCulture, $"    /// Accesses the native {type.Name}.{field.NativeName} field.");
                source.AppendLine("    /// </summary>");
                if (representation.StartsWith("__IncompleteArrayField<", StringComparison.Ordinal))
                {
                    Value element = Map(NativeBindingSelection.ArrayElement(representation)!, observed.ElementSize, null);
                    source.AppendLine("    /// <param name=\"address\">A live native object with enough trailing storage for every requested element.</param>");
                    source.AppendLine("    /// <param name=\"length\">The number of native elements to borrow.</param>");
                    source.AppendLine("    /// <returns>A view whose validity is bounded by the caller's native storage and lifetime.</returns>");
                    source.AppendLine(CultureInfo.InvariantCulture, $"    public static unsafe global::System.Span<{element.Code}> @Dangerous_{field.NativeName}(@{type.Name}* address, int length)");
                    source.AppendLine("    {");
                    source.AppendLine("        global::System.ArgumentOutOfRangeException.ThrowIfNegative(length);");
                    source.AppendLine("        if (address is null) { throw new global::System.ArgumentNullException(nameof(address)); }");
                    source.AppendLine();
                    source.AppendLine(CultureInfo.InvariantCulture, $"        return new((byte*)address + {observed.Offset}, length);");
                    source.AppendLine("    }");
                    continue;
                }

                Value value = Map(representation, observed.Size, observed.ElementSize);
                source.AppendLine(CultureInfo.InvariantCulture, $"    [global::System.Runtime.InteropServices.FieldOffset({observed.Offset})]");
                if (value.Code == "bool")
                {
                    source.AppendLine("    [global::System.Runtime.InteropServices.MarshalAs(global::System.Runtime.InteropServices.UnmanagedType.U1)]");
                }

                source.AppendLine(CultureInfo.InvariantCulture, $"    public {value.Code} @{field.NativeName};");
            }

            source.AppendLine("}");
            source.AppendLine();
        }

        private Value Map(string representation, int size, int? elementSize)
        {
            string resolved = NativeBindingSelection.ResolveAlias(catalog, representation);
            string? element = NativeBindingSelection.ArrayElement(resolved);
            Value value;
            if (element is not null)
            {
                if (elementSize is null && NativeBindingSelection.ArrayElement(NativeBindingSelection.ResolveAlias(catalog, element)) is not null)
                {
                    throw new FormatException($"The nested native array requires additional measured strides: {representation}.");
                }

                Value item = Map(element, elementSize ?? ArrayElementSize(resolved, size), null);
                if (size == 0 || size % item.Size != 0) { throw new FormatException($"Invalid native array extent for {representation}."); }

                int count = size / item.Size;
                if (!_arrays.TryGetValue((item.Code, count), out string? name))
                {
                    name = "NativeArray" + _arrays.Count.ToString(CultureInfo.InvariantCulture);
                    if (catalog.Types.ContainsKey(name) || catalog.Enums.ContainsKey(name))
                    {
                        throw new FormatException($"A native declaration conflicts with generated array {name}.");
                    }

                    _arrays.Add((item.Code, count), name);
                }

                value = new(name, size);
            }
            else if (layout.Types.TryGetValue(resolved, out NativeBindingTypeLayout? nested))
            {
                value = new("@" + resolved, nested.Size);
            }
            else if (resolved.EndsWith("::Type", StringComparison.Ordinal) && catalog.Enums.TryGetValue(resolved[..^6], out NativeBindingEnum? enumeration))
            {
                _enums.Add(resolved[..^6]);
                value = new("@" + resolved[..^6], EnumStorage(resolved[..^6]).Size);
            }
            else
            {
                value = resolved == "NodeTag" ? new("NodeTag", 4) : Scalar(resolved, size);
            }

            if (value.Size != size) { throw new FormatException($"Managed representation of {representation} has {value.Size} bytes; native field has {size}."); }

            return value;
        }

        private static int ArrayElementSize(string representation, int size)
        {
            string extent = representation[(representation.LastIndexOf(';') + 1)..^1].Trim();
            if (extent.EndsWith("usize", StringComparison.Ordinal)) { extent = extent[..^5]; }

            if (!int.TryParse(extent, NumberStyles.None, CultureInfo.InvariantCulture, out int count) || count <= 0 || size % count != 0)
            {
                throw new FormatException($"Invalid native array extent for {representation}.");
            }

            return size / count;
        }

        private Value EnumStorage(string name)
        {
            NativeBindingEnumLayout native = layout.Enums[name];
            string code = (native.Size, native.IsSigned) switch
            {
                (1, true) => "sbyte", (1, false) => "byte",
                (2, true) => "short", (2, false) => "ushort",
                (4, true) => "int", (4, false) => "uint",
                (8, true) => "long", (8, false) => "ulong",
                _ => throw new FormatException($"Unsupported native enum storage for {name}."),
            };
            return new(code, native.Size);
        }

        private Value Scalar(string representation, int measuredSize)
        {
            string resolved = NativeBindingSelection.ResolveAlias(catalog, representation);
            if (resolved.StartsWith("*mut ", StringComparison.Ordinal) || resolved.StartsWith("*const ", StringComparison.Ordinal) ||
                resolved.StartsWith("::core::option::Option<", StringComparison.Ordinal) && resolved.Contains("fn(", StringComparison.Ordinal))
            {
                return new("nint", layout.PointerSize);
            }

            return resolved switch
            {
                "bool" => new("bool", 1),
                "i8" or "::core::ffi::c_schar" => new("sbyte", 1),
                "u8" or "::core::ffi::c_uchar" => new("byte", 1),
                "::core::ffi::c_char" => new(layout.CharIsSigned ? "sbyte" : "byte", 1),
                "i16" or "::core::ffi::c_short" => new("short", 2),
                "u16" or "::core::ffi::c_ushort" => new("ushort", 2),
                "i32" or "::core::ffi::c_int" => new("int", 4),
                "u32" or "::core::ffi::c_uint" or "Oid" or "TransactionId" or "MultiXactId" => new("uint", 4),
                "i64" or "::core::ffi::c_longlong" => new("long", 8),
                "u64" or "::core::ffi::c_ulonglong" => new("ulong", 8),
                // Bindgen typedefs use their source target's primitive, e.g. uint64 becomes c_ulong
                // on Linux but unsigned long long on Windows. The selected field supplies its width.
                "::core::ffi::c_long" when measuredSize is 4 or 8 => new(measuredSize == 8 ? "long" : "int", measuredSize),
                "::core::ffi::c_ulong" when measuredSize is 4 or 8 => new(measuredSize == 8 ? "ulong" : "uint", measuredSize),
                "isize" => new("nint", layout.PointerSize),
                "usize" or "Datum" => new("nuint", layout.PointerSize),
                "f32" or "::core::ffi::c_float" => new("float", 4),
                "f64" or "::core::ffi::c_double" => new("double", 8),
                "i128" => new("global::System.Int128", 16),
                "u128" => new("global::System.UInt128", 16),
                _ => throw new FormatException($"No managed native representation for {representation}."),
            };
        }

        private static void WriteEnum(StringBuilder source, string name, Value storage, IReadOnlyDictionary<string, string> values)
        {
            if (storage.Code is not ("sbyte" or "byte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong"))
            {
                throw new FormatException($"Unsupported native enum representation {storage.Code} for {name}.");
            }

            bool signed = storage.Code is "sbyte" or "short" or "int" or "long";
            BigInteger limit = BigInteger.One << (storage.Size * 8 - (signed ? 1 : 0));
            foreach (string expression in values.Values)
            {
                if (!BigInteger.TryParse(expression, NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out BigInteger number) ||
                    number < (signed ? -limit : BigInteger.Zero) || number >= limit)
                {
                    throw new FormatException($"Invalid native enum value {name}: {expression}.");
                }
            }

            source.AppendLine("/// <summary>");
            source.AppendLine(CultureInfo.InvariantCulture, $"/// Preserves the pinned PostgreSQL {name} native constants.");
            source.AppendLine("/// </summary>");
            source.AppendLine(CultureInfo.InvariantCulture, $"public enum @{name} : {storage.Code}");
            source.AppendLine("{");
            foreach ((string member, string expression) in values)
            {
                source.AppendLine("    /// <summary>");
                source.AppendLine(CultureInfo.InvariantCulture, $"    /// Represents native {member}.");
                source.AppendLine("    /// </summary>");
                string suffix = storage.Code switch { "uint" => "U", "ulong" => "UL", "long" => "L", _ => string.Empty };
                source.AppendLine(CultureInfo.InvariantCulture, $"    @{member} = {expression}{suffix},");
            }

            source.AppendLine("}");
            source.AppendLine();
        }

        private sealed record Value(string Code, int Size);
    }
}
