<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <RootNamespace>Ankus.IntegrationTests</RootNamespace>
    <MSTestAnalysisMode>Recommended</MSTestAnalysisMode>
    <EnableMSTestSourceGeneration>true</EnableMSTestSourceGeneration>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../src/Ankus.Testing/Ankus.Testing.csproj" />
    <ProjectReference Include="../../src/Ankus.Tool/Ankus.Tool.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Hello/Ankus.Examples.Hello.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
