<Project Sdk="MSTest.Sdk">

  <PropertyGroup>
    <RootNamespace>Ankus.IntegrationTests</RootNamespace>
    <EnableMSTestSourceGeneration>true</EnableMSTestSourceGeneration>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
    <ProjectReference Include="../../src/Ankus.Testing/Ankus.Testing.csproj" />
    <ProjectReference Include="../../src/Ankus.Tool/Ankus.Tool.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Enums/Ankus.Examples.Enums.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.CustomTypes/Ankus.Examples.CustomTypes.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Composites/Ankus.Examples.Composites.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Hello/Ankus.Examples.Hello.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Operators/Ankus.Examples.Operators.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Sets/Ankus.Examples.Sets.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../../samples/Ankus.Examples.Ranges/Ankus.Examples.Ranges.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
