<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Named PostgreSQL composite types in functions, operators, aggregates, arrays and sets.</Description>
    <AnkusExtensionName>ankus_composites</AnkusExtensionName>
    <AnkusExtensionControlFile>$(MSBuildProjectDirectory)/ankus_composites.control</AnkusExtensionControlFile>
  </PropertyGroup>

  <Import Project="../../src/Ankus.Sdk/Ankus.Sdk.targets" />

</Project>
