<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Backend initialization without SQL function declarations.</Description>
    <AnkusExtensionName>ankus_initialization</AnkusExtensionName>
  </PropertyGroup>

  <Import Project="../../src/Ankus.Sdk/Ankus.Sdk.targets" />

</Project>
