using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using YamlDotNet.RepresentationModel;

namespace Ankus.DocGenerator;

/// <summary>
/// Converts DocFX's YAML model to linked type pages without loading extension code.
/// </summary>
internal sealed partial class ApiReferenceRenderer
{
    /// <summary>
    /// Identifies files owned by this generator for safe regeneration and stale-page removal.
    /// </summary>
    internal const string Marker = "<!-- Generated by Ankus.DocGenerator. -->";

    private readonly SortedDictionary<string, YamlMappingNode> _items = new(StringComparer.Ordinal);
    private readonly Dictionary<string, YamlMappingNode> _references = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _links = new(StringComparer.Ordinal);

    /// <summary>
    /// Loads the complete metadata graph and assigns stable URLs to types and overloaded members.
    /// </summary>
    /// <param name="metadataDirectory">The DocFX metadata directory.</param>
    internal ApiReferenceRenderer(string metadataDirectory)
    {
        foreach (string file in Directory.GetFiles(metadataDirectory, "*.yml").Order(StringComparer.Ordinal))
        {
            if (Path.GetFileName(file) == "toc.yml")
            {
                continue;
            }

            using var reader = new StringReader(File.ReadAllText(file));
            var yaml = new YamlStream();
            yaml.Load(reader);
            var root = (YamlMappingNode)yaml.Documents[0].RootNode;
            foreach (YamlMappingNode item in Sequence(root, "items").Cast<YamlMappingNode>())
            {
                _items.Add(Text(item, "uid"), item);
            }

            foreach (YamlMappingNode reference in Sequence(root, "references").Cast<YamlMappingNode>())
            {
                _references.TryAdd(Text(reference, "uid"), reference);
            }
        }

        foreach ((string uid, YamlMappingNode item) in _items.Where(static pair => IsPage(pair.Value)))
        {
            _links.Add(uid, "/api/" + Slug(uid) + "/");
            foreach (YamlNode child in Sequence(item, "children"))
            {
                string childUid = Scalar(child);
                if (_items.TryGetValue(childUid, out YamlMappingNode? member) && !IsPage(member))
                {
                    _links.Add(childUid, _links[uid] + "#" + Anchor(childUid));
                }
            }
        }

        if (_items.Keys.Any(uid => !_links.ContainsKey(uid)))
        {
            throw new InvalidOperationException("The API metadata contains declarations without a reference page or member anchor.");
        }
    }

    /// <summary>
    /// Gets the number of member declarations in the generated reference, including compiler-synthesized members.
    /// </summary>
    internal int MemberCount => _items.Values.Count(static item => !IsPage(item));

    /// <summary>
    /// Renders namespace and type pages in deterministic UID order.
    /// </summary>
    /// <returns>The generated filenames and Markdown content.</returns>
    internal IReadOnlyDictionary<string, string> Render()
    {
        var pages = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach ((string uid, YamlMappingNode item) in _items.Where(static pair => IsPage(pair.Value)))
        {
            var text = new StringBuilder();
            text.AppendLine("---");
            text.AppendLine("title: '" + Text(item, "name").Replace("'", "''", StringComparison.Ordinal) + "'");
            string fullName = Text(item, "fullName").Replace("'", "''", StringComparison.Ordinal);
            text.AppendLine("description: 'API reference for " + fullName + ".'");
            text.AppendLine("slug: api/" + Slug(uid));
            text.AppendLine("---");
            text.AppendLine(Marker);
            text.AppendLine();
            if (Text(item, "namespace") is { Length: > 0 } ns)
            {
                text.AppendLine("Namespace: " + Link(ns));
                text.AppendLine();
            }

            string[] assemblies = [.. Sequence(item, "assemblies").Select(Scalar)];
            if (assemblies.Length != 0)
            {
                text.AppendLine("Assembly: " + string.Join(", ", assemblies.Select(static name => "`" + name + ".dll`")));
                text.AppendLine();
            }

            AppendDeclaration(text, item);
            AppendLinks(text, item, "inheritance", "Inheritance");
            AppendLinks(text, item, "implements", "Implements");
            foreach (IGrouping<string, YamlMappingNode> group in Sequence(item, "children").Select(Scalar)
                .Where(_items.ContainsKey).Select(key => _items[key]).GroupBy(child => Text(child, "type")))
            {
                text.AppendLine("## " + Section(group.Key));
                text.AppendLine();
                foreach (YamlMappingNode child in group)
                {
                    string childUid = Text(child, "uid");
                    if (IsPage(child))
                    {
                        text.AppendLine("- " + Link(childUid));
                        continue;
                    }

                    text.AppendLine("<a id=\"" + Anchor(childUid) + "\"></a>");
                    text.AppendLine();
                    text.AppendLine("### " + WebUtility.HtmlEncode(Text(child, "name")));
                    text.AppendLine();
                    AppendDeclaration(text, child);
                }

                text.AppendLine();
            }

            pages.Add(Slug(uid) + ".md", text.ToString().Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd() + "\n");
        }

        if (pages.Count == 0)
        {
            throw new InvalidOperationException("DocFX produced no public API pages.");
        }

        return pages;
    }

    private void AppendDeclaration(StringBuilder output, YamlMappingNode item)
    {
        AppendText(output, Text(item, "summary"));
        if (Node(item, "syntax") is YamlMappingNode syntax)
        {
            if (Text(syntax, "content") is { Length: > 0 } content)
            {
                output.AppendLine("```csharp");
                output.AppendLine(content);
                output.AppendLine("```");
                output.AppendLine();
            }

            AppendParameters(output, syntax, "typeParameters", "Type parameters");
            AppendParameters(output, syntax, "parameters", "Parameters");
            string kind = Text(item, "type");
            if (kind != "Field" && Node(syntax, "return") is YamlMappingNode result && Text(result, "type") != "System.Void")
            {
                output.AppendLine((kind == "Property" ? "Value: " : "Returns: ") + Link(Text(result, "type")));
                output.AppendLine();
                AppendText(output, Text(result, "description"));
            }
        }

        if (Sequence(item, "exceptions").Count != 0)
        {
            output.AppendLine("Exceptions:");
            output.AppendLine();
            foreach (YamlMappingNode exception in Sequence(item, "exceptions").Cast<YamlMappingNode>())
            {
                output.AppendLine("- " + Link(Text(exception, "type")) + ": " + ConvertText(Text(exception, "description")));
            }

            output.AppendLine();
        }

        AppendText(output, Text(item, "remarks"));
        foreach (YamlNode example in Sequence(item, "example"))
        {
            AppendText(output, Scalar(example));
        }
    }

    private void AppendParameters(StringBuilder output, YamlMappingNode syntax, string key, string title)
    {
        if (Sequence(syntax, key).Count == 0)
        {
            return;
        }

        output.AppendLine(title + ":");
        output.AppendLine();
        foreach (YamlMappingNode parameter in Sequence(syntax, key).Cast<YamlMappingNode>())
        {
            output.AppendLine("`" + Text(parameter, "id") + "`" +
                (Text(parameter, "type") is { Length: > 0 } type ? " — " + Link(type) : string.Empty));
            output.AppendLine();
            AppendText(output, Text(parameter, "description"));
        }
    }

    private void AppendLinks(StringBuilder output, YamlMappingNode item, string key, string title)
    {
        if (Sequence(item, key).Count != 0)
        {
            output.AppendLine(title + ": " + string.Join(", ", Sequence(item, key).Select(node => Link(Scalar(node)))));
            output.AppendLine();
        }
    }

    private void AppendText(StringBuilder output, string text)
    {
        if (!string.IsNullOrWhiteSpace(text))
        {
            output.AppendLine(ConvertText(text));
            output.AppendLine();
        }
    }

    private string ConvertText(string text)
        => XrefPattern().Replace(text, match => Link(WebUtility.HtmlDecode(Uri.UnescapeDataString(match.Groups[1].Value))));

    private string Link(string uid)
    {
        YamlMappingNode? reference = _items.GetValueOrDefault(uid) ?? _references.GetValueOrDefault(uid);
        string label = reference is null ? uid : Text(reference, "name");
        label = WebUtility.HtmlEncode(label.Length == 0 ? uid : label);
        if (_links.TryGetValue(uid, out string? link))
        {
            return $"[{label}]({link})";
        }

        if (reference is not null && Text(reference, "href") is { Length: > 0 } href &&
            Uri.TryCreate(href, UriKind.Absolute, out Uri? uri) && uri.Scheme == "https")
        {
            return $"[{label}]({uri.AbsoluteUri})";
        }

        return "<code>" + label + "</code>";
    }

    private static string Section(string kind) => kind switch
    {
        "Class" => "Classes", "Struct" => "Structs", "Interface" => "Interfaces", "Enum" => "Enums",
        "Delegate" => "Delegates", "Constructor" => "Constructors", "Method" => "Methods", "Property" => "Properties",
        "Field" => "Fields", "Event" => "Events", "Operator" => "Operators", _ => "Members",
    };

    private static bool IsPage(YamlMappingNode node)
        => Text(node, "type") is "Namespace" or "Class" or "Struct" or "Interface" or "Enum" or "Delegate";

    private static string Slug(string uid)
        => string.Concat(uid.Select(static c => char.IsAsciiLetterOrDigit(c) || c == '.' ? char.ToLowerInvariant(c) : '-'));

    private static string Anchor(string uid)
        => "member-" + Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(uid)))[..16];

    private static string Text(YamlMappingNode node, string key) => Node(node, key) is YamlScalarNode value ? Scalar(value) : string.Empty;

    private static string Scalar(YamlNode node) => ((YamlScalarNode)node).Value ?? string.Empty;

    private static YamlNode? Node(YamlMappingNode node, string key)
        => node.Children.TryGetValue(new YamlScalarNode(key), out YamlNode? value) ? value : null;

    private static IList<YamlNode> Sequence(YamlMappingNode node, string key)
        => Node(node, key) is YamlSequenceNode sequence ? sequence.Children : [];

    [GeneratedRegex("<xref\\s+href=\"([^\"]+)\"[^>]*>(?:</xref>)?")]
    private static partial Regex XrefPattern();
}
